### ISSUE TITLE
Adding .readme file

### ISSUE THREAD

**Issue by VirdanTheBurden** [cat-dev-group/Catlang#1]
Hey lads.

We need a readme file. We must spread the word of catlang through our READMEs, otherwise nobody will take us seriously.

**Comment by Kronifer** [comment]
Just make a new branch you have write access

**Comment by VirdanTheBurden** [comment]
It's good practice to make it an issue first before you PR, I'm trying to stick with that github workflow.

**Comment by VirdanTheBurden** [comment]
alright, readme is there, closing issue
